### ISSUE TITLE
How to visualize the features ?

### ISSUE THREAD

**Issue by YaoZhang93** [wulalago/DAF3D#2]
Hi, thanks for your awesome work, especially the visualization!
Could you please tell how did you visualize the feature maps of DAF as illustrated in Fig. 2 and Fig. 7?
Are they obtained by the mean value along channels for each feature map?
Did you normalize the values before visualization?
Thanks.

**Comment by wulalago** [comment]
Sorry to reply so late.  
Firstly, We select one of the channels in the entire featrue maps, e.g. (C, D, W, H) -> (1, D, W, H). Then, we extract a slice of the whole volume. Finally, we normalize the slice and plot it. 
It is noted that some channels in the feature maps or the attention maps show a inverse appearance to the visualization in the paper due to the prossiable negative calculation in the deep neural network. Thereby we choose the 'positive'(high values represent the high responses of neuron) feature maps as the final subject showing in paper to prevent confusion.
Hope this will help you.

**Comment by wulalago** [comment]
> Hi, thanks for your awesome work, especially the visualization!
> Could you please tell how did you visualize the feature maps of DAF as illustrated in Fig. 2 and Fig. 7?
> Are they obtained by the mean value along channels for each feature map?
> Did you normalize the values before visualization?
> Thanks.

Sorry to reply so late.
Firstly, We select one of the channels in the entire featrue maps, e.g. (C, D, W, H) -> (1, D, W, H). Then, we extract a slice of the whole volume. Finally, we normalize the slice and plot it.
It is noted that some channels in the feature maps or the attention maps show a inverse appearance to the visualization in the paper due to the prossiable negative calculation in the deep neural network. Thereby we choose the 'positive'(high values represent the high responses of neuron) feature maps as the final subject showing in paper to prevent confusion.
Hope this will help you.

**Comment by YaoZhang93** [comment]
Thanks for your reply.
Happy New Year!
